-- Global default positions per industry
-- Run via Supabase Dashboard > SQL Editor
--
-- This creates a global_industry_roles table for positions that apply to all
-- organisations, and seeds it with the platform default positions.
-- The app falls back to INDUSTRY_POSITIONS (compiled constant) when this
-- table is empty, so this seed is optional but recommended for persistence.

-- ── 1. Create table ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.global_industry_roles (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  industry     TEXT NOT NULL,
  role_level   TEXT NOT NULL CHECK (role_level IN ('worker','supervisor','manager')),
  role_name    TEXT NOT NULL,
  sort_order   INTEGER,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (industry, role_name)
);

ALTER TABLE public.global_industry_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read global roles"
  ON public.global_industry_roles FOR SELECT USING (true);

CREATE POLICY "Super admin can manage global roles"
  ON public.global_industry_roles FOR ALL
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'super_admin'));

-- ── 2. Seed positions ───────────────────────────────────────────────────────
INSERT INTO public.global_industry_roles (industry, role_level, role_name, sort_order) VALUES
-- ADMINISTRATION
('Administration','worker','Administration Assistant',1),
('Administration','worker','Data Entry Clerk',2),
('Administration','worker','Receptionist',3),
('Administration','worker','Office Assistant',4),
('Administration','worker','Filing Clerk',5),
('Administration','worker','Maintenance Officer',6),
('Administration','supervisor','Administration Supervisor',7),
('Administration','supervisor','Office Supervisor',7),
('Administration','supervisor','Team Leader',8),
('Administration','manager','Office Manager',9),
('Administration','manager','Administration Manager',10),
('Administration','manager','Operations Manager',11),
-- AGED CARE
('Aged Care','worker','Personal Carer',1),
('Aged Care','worker','Support Worker',2),
('Aged Care','worker','Cleaner',3),
('Aged Care','worker','Laundry Assistant',4),
('Aged Care','worker','Kitchen Assistant',5),
('Aged Care','worker','Driver',6),
('Aged Care','worker','Activity Assistant',7),
('Aged Care','worker','Maintenance Officer',8),
('Aged Care','supervisor','Care Supervisor',9),
('Aged Care','supervisor','Shift Supervisor',9),
('Aged Care','supervisor','Team Leader',10),
('Aged Care','manager','Care Manager',11),
('Aged Care','manager','Facility Manager',12),
('Aged Care','manager','Operations Manager',13),
-- ALLIED HEALTH
('Allied Health','worker','Allied Health Assistant',1),
('Allied Health','worker','Therapy Assistant',2),
('Allied Health','worker','Receptionist',3),
('Allied Health','worker','Cleaner',4),
('Allied Health','worker','Maintenance Officer',5),
('Allied Health','supervisor','Allied Health Supervisor',6),
('Allied Health','supervisor','Team Leader',6),
('Allied Health','manager','Practice Manager',7),
('Allied Health','manager','Allied Health Manager',8),
('Allied Health','manager','Operations Manager',9),
-- CLINICAL
('Clinical','worker','Clinic Assistant',1),
('Clinical','worker','Receptionist',2),
('Clinical','worker','Sterilisation Technician',3),
('Clinical','worker','Cleaner',4),
('Clinical','worker','Administration Assistant',5),
('Clinical','worker','Maintenance Officer',6),
('Clinical','supervisor','Clinic Supervisor',7),
('Clinical','supervisor','Administration Supervisor',7),
('Clinical','supervisor','Team Leader',8),
('Clinical','manager','Practice Manager',9),
('Clinical','manager','Clinic Manager',10),
('Clinical','manager','Operations Manager',11),
-- COMMUNITY SERVICES
('Community Services','worker','Community Worker',1),
('Community Services','worker','Support Worker',2),
('Community Services','worker','Driver',3),
('Community Services','worker','Cleaner',4),
('Community Services','worker','Administration Assistant',5),
('Community Services','worker','Maintenance Officer',6),
('Community Services','supervisor','Community Supervisor',7),
('Community Services','supervisor','Team Leader',7),
('Community Services','supervisor','Shift Supervisor',8),
('Community Services','manager','Program Manager',9),
('Community Services','manager','Community Services Manager',10),
('Community Services','manager','Operations Manager',11),
-- COMPLIANCE & QUALITY
('Compliance & Quality','worker','Compliance Assistant',1),
('Compliance & Quality','worker','Quality Assistant',2),
('Compliance & Quality','worker','Administration Assistant',3),
('Compliance & Quality','worker','Auditor Assistant',4),
('Compliance & Quality','worker','Maintenance Officer',5),
('Compliance & Quality','supervisor','Compliance Supervisor',6),
('Compliance & Quality','supervisor','Quality Supervisor',6),
('Compliance & Quality','supervisor','Team Leader',7),
('Compliance & Quality','manager','Compliance Manager',8),
('Compliance & Quality','manager','Quality Manager',9),
('Compliance & Quality','manager','Risk Manager',10),
-- CONSTRUCTION
('Construction','worker','Labourer',1),
('Construction','worker','Trades Assistant',2),
('Construction','worker','Cleaner',3),
('Construction','worker','Site Hand',4),
('Construction','worker','Scaffolder',5),
('Construction','worker','Maintenance Officer',6),
('Construction','supervisor','Site Supervisor',7),
('Construction','supervisor','Foreperson',7),
('Construction','supervisor','Team Leader',8),
('Construction','manager','Site Manager',9),
('Construction','manager','Project Manager',10),
('Construction','manager','Construction Manager',11),
-- DISABILITY CARE
('Disability Care','worker','Support Worker',1),
('Disability Care','worker','Personal Carer',2),
('Disability Care','worker','Driver',3),
('Disability Care','worker','Cleaner',4),
('Disability Care','worker','Activity Assistant',5),
('Disability Care','worker','Maintenance Officer',6),
('Disability Care','supervisor','Support Supervisor',7),
('Disability Care','supervisor','Team Leader',7),
('Disability Care','supervisor','Shift Supervisor',8),
('Disability Care','manager','Service Manager',9),
('Disability Care','manager','Disability Care Manager',10),
('Disability Care','manager','Operations Manager',11),
-- ENGINEERING
('Engineering','worker','Engineering Assistant',1),
('Engineering','worker','Technician',2),
('Engineering','worker','Maintenance Officer',3),
('Engineering','worker','Trades Assistant',4),
('Engineering','supervisor','Engineering Supervisor',5),
('Engineering','supervisor','Maintenance Supervisor',6),
('Engineering','supervisor','Team Leader',7),
('Engineering','manager','Engineering Manager',8),
('Engineering','manager','Maintenance Manager',9),
('Engineering','manager','Operations Manager',10),
-- FOOD & BEVERAGE
('Food & Beverage','worker','Kitchen Hand',1),
('Food & Beverage','worker','Waiter',2),
('Food & Beverage','worker','Barista',3),
('Food & Beverage','worker','Bar Staff',4),
('Food & Beverage','worker','Chef',5),
('Food & Beverage','worker','Cook',6),
('Food & Beverage','worker','Dishwasher',7),
('Food & Beverage','worker','Food Runner',8),
('Food & Beverage','worker','Maintenance Officer',9),
('Food & Beverage','supervisor','F&B Supervisor',10),
('Food & Beverage','supervisor','Kitchen Supervisor',10),
('Food & Beverage','supervisor','Floor Supervisor',11),
('Food & Beverage','manager','F&B Manager',12),
('Food & Beverage','manager','Restaurant Manager',13),
('Food & Beverage','manager','Kitchen Manager',14),
-- HOSPITALITY
('Hospitality','worker','Cleaner',1),
('Hospitality','worker','Kitchen Aid',2),
('Hospitality','worker','Waiter',3),
('Hospitality','worker','Bar Tender',4),
('Hospitality','worker','Chef',5),
('Hospitality','worker','Reception',6),
('Hospitality','worker','Plumber',7),
('Hospitality','worker','Electrician',8),
('Hospitality','worker','Driver',9),
('Hospitality','worker','Finance',10),
('Hospitality','worker','Housekeeper',11),
('Hospitality','worker','Room Attendant',12),
('Hospitality','worker','Laundry Staff',13),
('Hospitality','worker','Barista',14),
('Hospitality','worker','Maintenance Officer',15),
('Hospitality','supervisor','Housekeeping Supervisor',16),
('Hospitality','supervisor','F&B Supervisor',16),
('Hospitality','supervisor','Front Desk Supervisor',17),
('Hospitality','supervisor','Kitchen Supervisor',18),
('Hospitality','manager','Operations Manager',19),
('Hospitality','manager','F&B Manager',20),
('Hospitality','manager','Housekeeping Manager',21),
('Hospitality','manager','Front Office Manager',22),
('Hospitality','manager','General Manager',23),
-- HOUSEKEEPING
('Housekeeping','worker','Housekeeper',1),
('Housekeeping','worker','Room Attendant',2),
('Housekeeping','worker','Laundry Staff',3),
('Housekeeping','worker','Cleaner',4),
('Housekeeping','worker','Linen Assistant',5),
('Housekeeping','worker','Maintenance Officer',6),
('Housekeeping','supervisor','Housekeeping Supervisor',7),
('Housekeeping','supervisor','Laundry Supervisor',7),
('Housekeeping','supervisor','Team Leader',8),
('Housekeeping','manager','Housekeeping Manager',9),
('Housekeeping','manager','Operations Manager',10),
-- IT & TECHNOLOGY
('IT & Technology','worker','IT Support Officer',1),
('IT & Technology','worker','Help Desk Officer',2),
('IT & Technology','worker','Data Entry Clerk',3),
('IT & Technology','worker','Systems Assistant',4),
('IT & Technology','worker','Maintenance Officer',5),
('IT & Technology','supervisor','IT Supervisor',6),
('IT & Technology','supervisor','Help Desk Supervisor',6),
('IT & Technology','supervisor','Team Leader',7),
('IT & Technology','manager','IT Manager',8),
('IT & Technology','manager','Systems Manager',9),
('IT & Technology','manager','Operations Manager',10),
-- MANUFACTURING
('Manufacturing','worker','Production Worker',1),
('Manufacturing','worker','Machine Operator',2),
('Manufacturing','worker','Quality Inspector',3),
('Manufacturing','worker','Packer',4),
('Manufacturing','worker','Forklift Operator',5),
('Manufacturing','worker','Cleaner',6),
('Manufacturing','worker','Maintenance Officer',7),
('Manufacturing','supervisor','Production Supervisor',8),
('Manufacturing','supervisor','Quality Supervisor',8),
('Manufacturing','supervisor','Shift Supervisor',9),
('Manufacturing','manager','Production Manager',10),
('Manufacturing','manager','Plant Manager',11),
('Manufacturing','manager','Operations Manager',12),
-- MINING & RESOURCES
('Mining & Resources','worker','Mining Labourer',1),
('Mining & Resources','worker','Driller Offsider',2),
('Mining & Resources','worker','Trades Assistant',3),
('Mining & Resources','worker','Safety Officer',4),
('Mining & Resources','worker','Cleaner',5),
('Mining & Resources','worker','Maintenance Officer',6),
('Mining & Resources','supervisor','Mine Supervisor',7),
('Mining & Resources','supervisor','Shift Supervisor',7),
('Mining & Resources','supervisor','Team Leader',8),
('Mining & Resources','manager','Mine Manager',9),
('Mining & Resources','manager','Site Manager',10),
('Mining & Resources','manager','Operations Manager',11),
-- NDIS
('NDIS','worker','Support Worker',1),
('NDIS','worker','Personal Carer',2),
('NDIS','worker','Gardener',3),
('NDIS','worker','Cleaner',4),
('NDIS','worker','Driver',5),
('NDIS','worker','Activity Assistant',6),
('NDIS','worker','Community Access Worker',7),
('NDIS','worker','Maintenance Officer',8),
('NDIS','supervisor','Support Supervisor',9),
('NDIS','supervisor','Team Leader',9),
('NDIS','supervisor','Shift Supervisor',10),
('NDIS','manager','Service Manager',11),
('NDIS','manager','NDIS Manager',12),
('NDIS','manager','Operations Manager',13),
-- OIL & GAS
('Oil & Gas','worker','Field Technician',1),
('Oil & Gas','worker','Trades Assistant',2),
('Oil & Gas','worker','Safety Officer',3),
('Oil & Gas','worker','Cleaner',4),
('Oil & Gas','worker','Labourer',5),
('Oil & Gas','worker','Maintenance Officer',6),
('Oil & Gas','supervisor','Field Supervisor',7),
('Oil & Gas','supervisor','Site Supervisor',7),
('Oil & Gas','supervisor','Team Leader',8),
('Oil & Gas','manager','Field Manager',9),
('Oil & Gas','manager','Site Manager',10),
('Oil & Gas','manager','Operations Manager',11),
-- PROJECT MANAGEMENT
('Project Management','worker','Project Assistant',1),
('Project Management','worker','Administration Assistant',2),
('Project Management','worker','Site Assistant',3),
('Project Management','worker','Document Controller',4),
('Project Management','worker','Maintenance Officer',5),
('Project Management','supervisor','Project Supervisor',6),
('Project Management','supervisor','Team Leader',6),
('Project Management','supervisor','Site Supervisor',7),
('Project Management','manager','Project Manager',8),
('Project Management','manager','Senior Project Manager',9),
('Project Management','manager','Operations Manager',10),
-- RETAIL
('Retail','worker','Sales Assistant',1),
('Retail','worker','Cashier',2),
('Retail','worker','Stock Room Assistant',3),
('Retail','worker','Cleaner',4),
('Retail','worker','Customer Service Officer',5),
('Retail','worker','Maintenance Officer',6),
('Retail','supervisor','Retail Supervisor',7),
('Retail','supervisor','Floor Supervisor',7),
('Retail','supervisor','Team Leader',8),
('Retail','manager','Store Manager',9),
('Retail','manager','Retail Manager',10),
('Retail','manager','Operations Manager',11),
-- SECURITY
('Security','worker','Security Officer',1),
('Security','worker','Control Room Operator',2),
('Security','worker','Concierge',3),
('Security','worker','Patrol Officer',4),
('Security','worker','Maintenance Officer',5),
('Security','supervisor','Security Supervisor',6),
('Security','supervisor','Shift Supervisor',6),
('Security','supervisor','Team Leader',7),
('Security','manager','Security Manager',8),
('Security','manager','Operations Manager',9),
('Security','manager','Site Manager',10),
-- TRANSPORT & LOGISTICS
('Transport & Logistics','worker','Driver',1),
('Transport & Logistics','worker','Forklift Operator',2),
('Transport & Logistics','worker','Warehouse Assistant',3),
('Transport & Logistics','worker','Picker Packer',4),
('Transport & Logistics','worker','Delivery Officer',5),
('Transport & Logistics','worker','Cleaner',6),
('Transport & Logistics','worker','Maintenance Officer',7),
('Transport & Logistics','supervisor','Transport Supervisor',8),
('Transport & Logistics','supervisor','Warehouse Supervisor',8),
('Transport & Logistics','supervisor','Shift Supervisor',9),
('Transport & Logistics','manager','Transport Manager',10),
('Transport & Logistics','manager','Logistics Manager',11),
('Transport & Logistics','manager','Warehouse Manager',12)

ON CONFLICT (industry, role_name) DO NOTHING;

-- Also ensure all industries exist in global_industries
INSERT INTO public.global_industries (name, created_by, created_at)
SELECT DISTINCT industry, 'system', NOW()
FROM public.global_industry_roles
ON CONFLICT DO NOTHING;
